# Settings
name: "WikiFreaks"
description: "an open repository of Wikipedia data"
creation_date: "May-June 2023"

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"
