# Site settings
site_name: "WikiFreaks"
site_description: ""
creation_date: "May-June 2023"

baseurl: "/wikifreaks" # the subpath of your site, e.g. /blog/

address: |
    Box 352840 - Mary Gates Hall, Ste. 370
    Seattle
    Washington

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"
